main: me.adelemphii.qolcommands.QOLCommands
name: QOLCommands
author: Adelemphii
version: ${project.version}
api-version: 1.13

commands:
  sit:
    description: Using /sit you can sit where you are!
  roll:
    description: Using /roll <number> will allow you to roll a random number for everyone in range to see!
  qolreload:
    description: Used to reload the config file!
  broadcastroll:
    description: Using /broadcastroll <number> will allow you to roll a random number but it will broadcast to everyone on the server!
    aliases:
      - broll
  carry:
    description: Using /carry <player> will allow you to pick up a nearby player and carry them around!
  walk:
    description: Using /walk will allow you to walk at a slower speed!
  qolcommands:
    description: Shows the help menu with all the commands!
